global using CommonBasicLibraries.CollectionClasses;
global using bb = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using ff = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using BasicBlazorLibrary.Components.Basic;
global using Microsoft.AspNetCore.Components;
global using BasicBlazorLibrary.Components.BaseClasses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using cc = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;