global using CommonBasicLibraries.CollectionClasses;
global using bb = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using ff = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using BasicBlazorLibrary.Components.Basic;
global using Microsoft.AspNetCore.Components;
global using BasicBlazorLibrary.Components.BaseClasses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using cc = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using CommonBasicLibraries.BasicDateTimeProcesses;
global using dd = NewTestamentWasm.Mocks.GlobalMock;
global using NewTestament5DayLibrary.Core.Services;
global using NewTestament5DayLibrary.Core.Models;
global using NewTestamentWasm.Mocks;
global using BibleContentLibrary;
global using BibleContentLibrary.TranslationServices;
global using NewTestamentWasm.Services;
global using Reminders.BibleBlazorCoreLibrary.DataAccess;
global using Reminders.BibleCoreLibrary.DataAccess;
global using BasicBlazorLibrary.Helpers; //not common enough to put under globals for now.
global using NewTestamentWasm.TranslationHelpers;
global using BasicBlazorLibrary.Components.NavigationMenus;
global using BibleDatabaseLibrary.Entities;
global using BibleDatabaseLibrary.Services;
global using Microsoft.JSInterop;
